<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-15T19:35:49 GMT-08:00" name="Suite" finished-at="2022-01-15T19:36:20 GMT-08:00" duration-ms="31443">
    <groups>
    </groups>
    <test started-at="2022-01-15T19:35:49 GMT-08:00" name="Test" finished-at="2022-01-15T19:36:20 GMT-08:00" duration-ms="31443">
      <class name="Test.onlyone">
        <test-method is-config="true" signature="before5()[pri:0, instance:Test.onlyone@5a56cdac]" started-at="2022-01-15T19:36:01 GMT-08:00" name="before5" finished-at="2022-01-15T19:36:05 GMT-08:00" duration-ms="4117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before5 -->
        <test-method signature="only1()[pri:0, instance:Test.onlyone@5a56cdac]" started-at="2022-01-15T19:36:05 GMT-08:00" name="only1" finished-at="2022-01-15T19:36:06 GMT-08:00" duration-ms="1036" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.onlyone.only1(onlyone.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- only1 -->
        <test-method is-config="true" signature="after5()[pri:0, instance:Test.onlyone@5a56cdac]" started-at="2022-01-15T19:36:06 GMT-08:00" name="after5" finished-at="2022-01-15T19:36:06 GMT-08:00" duration-ms="225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after5 -->
      </class> <!-- Test.onlyone -->
      <class name="Test.pastInputDate">
        <test-method is-config="true" signature="before5()[pri:0, instance:Test.pastInputDate@7c711375]" started-at="2022-01-15T19:36:06 GMT-08:00" name="before5" finished-at="2022-01-15T19:36:12 GMT-08:00" duration-ms="5475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before5 -->
        <test-method signature="pastInput()[pri:0, instance:Test.pastInputDate@7c711375]" started-at="2022-01-15T19:36:12 GMT-08:00" name="pastInput" finished-at="2022-01-15T19:36:13 GMT-08:00" duration-ms="1007" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.pastInputDate.pastInput(pastInputDate.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pastInput -->
        <test-method is-config="true" signature="after5()[pri:0, instance:Test.pastInputDate@7c711375]" started-at="2022-01-15T19:36:13 GMT-08:00" name="after5" finished-at="2022-01-15T19:36:13 GMT-08:00" duration-ms="276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after5 -->
      </class> <!-- Test.pastInputDate -->
      <class name="Test.noSeparator">
        <test-method is-config="true" signature="before5()[pri:0, instance:Test.noSeparator@593aaf41]" started-at="2022-01-15T19:35:56 GMT-08:00" name="before5" finished-at="2022-01-15T19:36:00 GMT-08:00" duration-ms="3935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before5 -->
        <test-method signature="noSepar()[pri:0, instance:Test.noSeparator@593aaf41]" started-at="2022-01-15T19:36:00 GMT-08:00" name="noSepar" finished-at="2022-01-15T19:36:01 GMT-08:00" duration-ms="932" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.noSeparator.noSepar(noSeparator.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noSepar -->
        <test-method is-config="true" signature="after5()[pri:0, instance:Test.noSeparator@593aaf41]" started-at="2022-01-15T19:36:01 GMT-08:00" name="after5" finished-at="2022-01-15T19:36:01 GMT-08:00" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after5 -->
      </class> <!-- Test.noSeparator -->
      <class name="Test.year5Digits">
        <test-method is-config="true" signature="before5()[pri:0, instance:Test.year5Digits@57cf54e1]" started-at="2022-01-15T19:36:13 GMT-08:00" name="before5" finished-at="2022-01-15T19:36:19 GMT-08:00" duration-ms="6216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before5 -->
        <test-method signature="yr5dgts()[pri:0, instance:Test.year5Digits@57cf54e1]" started-at="2022-01-15T19:36:19 GMT-08:00" name="yr5dgts" finished-at="2022-01-15T19:36:20 GMT-08:00" duration-ms="889" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.year5Digits.yr5dgts(year5Digits.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- yr5dgts -->
        <test-method is-config="true" signature="after5()[pri:0, instance:Test.year5Digits@57cf54e1]" started-at="2022-01-15T19:36:20 GMT-08:00" name="after5" finished-at="2022-01-15T19:36:20 GMT-08:00" duration-ms="276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after5 -->
      </class> <!-- Test.year5Digits -->
      <class name="Test.correctInputDate">
        <test-method is-config="true" signature="before5()[pri:0, instance:Test.correctInputDate@2ed2d9cb]" started-at="2022-01-15T19:35:49 GMT-08:00" name="before5" finished-at="2022-01-15T19:35:54 GMT-08:00" duration-ms="5556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before5 -->
        <test-method signature="correctInput()[pri:0, instance:Test.correctInputDate@2ed2d9cb]" started-at="2022-01-15T19:35:54 GMT-08:00" name="correctInput" finished-at="2022-01-15T19:35:55 GMT-08:00" duration-ms="944" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- correctInput -->
        <test-method is-config="true" signature="after5()[pri:0, instance:Test.correctInputDate@2ed2d9cb]" started-at="2022-01-15T19:35:55 GMT-08:00" name="after5" finished-at="2022-01-15T19:35:56 GMT-08:00" duration-ms="253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after5 -->
      </class> <!-- Test.correctInputDate -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
